### ISSUE TITLE
Can't install, help!

### ISSUE THREAD

**Issue by heyitswin** [flovan/headstart#51]
Hi there, having trouble installing here and haven't had success with clearing cache. Gist of npm debug log here - https://gist.github.com/heyitswin/6407dbee2750fd5f0757

**Comment by flovan** [comment]
Weird.. I just tried installing on my machine and had no problems. I don't see anything specific going wrong in the debug log with all that's going on in there, so I'll first try some basic fixes:

1. Make sure your system meets [the requirements](http://headstart.io/installation#requirements).
2. Were you running the install command with `sudo`? If not try running `sudo npm install -g headstart`.

if those are ok, maybe provide me with your OS, Node and NPM version. I'll check the debug log more thoroughly and maybe setup a Virtual machine to match your setup as a last resort.

**Comment by heyitswin** [comment]
Yep, double checked the requirements and I do have them. I was installing with `sudo`. I'm on OSX 10.9.5.

Here's a sample of what's going on when I try to install:
`npm WARN deprecated gulp-rimraf@0.1.1: Use npmjs.org/del instead, see https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "headstart"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "headstart"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "headstart"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "headstart"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

> ws@0.5.0 install /usr/local/lib/node_modules/headstart/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN deprecated tap-consumer@0.0.1: this is merged into the 'tap' module now
npm WARN deprecated tap-results@0.0.2: this is merged into the 'tap' module now

> phantomjs@1.9.15 install /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [========================================] 99% 0.0s
Received 9187K total.
Extracting zip contents
Removing /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/lib/phantom
Copying extracted folder /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1424338906867/phantomjs-1.9.8-macosx -> /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/lib/phantom/bin/phantomjs

> gifsicle@2.0.1 postinstall /usr/local/lib/node_modules/headstart/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully


> optipng-bin@2.0.4 postinstall /usr/local/lib/node_modules/headstart/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@2.0.2 postinstall /usr/local/lib/node_modules/headstart/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> pngquant-bin@2.0.3 postinstall /usr/local/lib/node_modules/headstart/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> ws@0.4.31 install /usr/local/lib/node_modules/headstart/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/therealwin/Sites/testy/npm-debug.log
`

**Comment by flovan** [comment]
Dang, I was hoping that it was something easy :sob:
I will look into this tonight after I get home. I'm still at work atm and can't fit this in unfortunately.

**Comment by heyitswin** [comment]
No worries, thanks for the speedy updates!

**Comment by flovan** [comment]
I just noticed you are running the latest Node and NPM (I'm at v0.10.25 and 2.1.7 here at work), so maybe that's what's broken. I'll upgrade my machine at home (I can't afford to mess up this one) and maybe by doing so I'll be able to replicate (and fix!) this problem.

**Comment by flovan** [comment]
@heyitswin I just updated my computer at home and had no problems at all with the installation.

As I don't have access to an OS X 10.9.x installation atm, can you try these steps again before I go through the trouble of finding out how to put together an OS X Virtual Machine:

1. `sudo npm cache clean -f`
2. `sudo npm uninstall -g headstart` (this probably won't do anything since it wasn't installed yet)
3. `sudo npm install -g headstart`

I always prefer double or triple checking these things before going the extra mile. I hope you don't mind :smile:

**Comment by heyitswin** [comment]
Tried again and no avail, though oddly when I did the uninstall i did get a `unbuild headstart@1.3.2`

Win-Lins-MacBook-Air:test therealwin$ sudo npm cache clean -f
Password:
npm WARN using --force I sure hope you know what you are doing.
Win-Lins-MacBook-Air:test therealwin$ sudo npm uninstall -g headstart
unbuild headstart@1.3.2
Win-Lins-MacBook-Air:test therealwin$ sudo npm install
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /Users/therealwin/Sites/test/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/Users/therealwin/Sites/test/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/therealwin/Sites/test/npm-debug.log
Win-Lins-MacBook-Air:test therealwin$ sudo nmp install -g headstart
sudo: nmp: command not found
Win-Lins-MacBook-Air:test therealwin$ sudo npm install -g headstart
npm WARN deprecated gulp-rimraf@0.1.1: Use npmjs.org/del instead, see https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "headstart"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "headstart"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "headstart"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

> ws@0.5.0 install /usr/local/lib/node_modules/headstart/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN deprecated tap-consumer@0.0.1: this is merged into the 'tap' module now
npm WARN deprecated tap-results@0.0.2: this is merged into the 'tap' module now

> phantomjs@1.9.15 install /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [=======================================-] 98% 0.0s
Received 9187K total.
Extracting zip contents
Removing /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/lib/phantom
Copying extracted folder /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1424393443853/phantomjs-1.9.8-macosx -> /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/headstart/node_modules/gulp-uncss/node_modules/uncss/node_modules/phantomjs/lib/phantom/bin/phantomjs

> optipng-bin@2.0.4 postinstall /usr/local/lib/node_modules/headstart/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@2.0.2 postinstall /usr/local/lib/node_modules/headstart/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@2.0.1 postinstall /usr/local/lib/node_modules/headstart/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully


> pngquant-bin@2.0.3 postinstall /usr/local/lib/node_modules/headstart/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> ws@0.4.31 install /usr/local/lib/node_modules/headstart/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/therealwin/Sites/test/npm-debug.log

**Comment by flovan** [comment]
Ugh this really bums me out. I don't understand what's going wrong in there at all. It throws some errors, then just goes on installing like nothing happened, and then errors out again :/
Can you try installing over the installation, or maybe just run `hs` and see if you get any output (maybe it succeeded, since it's unbuilding)?

I'm going to download a 10.9 image and try to install it into a VM like I said. I won't be able to do it today though. I'm in the middle of regular weekend and having family over and remodeling a house, ugh! Too little time :cry:. Please bare with me until I figure something out.

Another thing you can try (if you feel like it) is [downloading the repo as a ZIP](https://github.com/flovan/headstart/archive/master.zip), unpacking it somewhere safe (maybe htdocs or something) and then symlinking it with NPM. This makes the folder as if it were installed. Steps to take:
- `cd` into the folder with the repo contents
- install the dependencies with `sudo npm install` (if it errors out here as well, you can skip the other steps as this is mandatory)
- `sudo npm link` to make the symlink
- test if the installation succeeded by running `hs` and see if the CLI information is logged out.

**Comment by flovan** [comment]
@heyitswin I think it might be due to node 0.12. I'm testing something else here at home and I ran into and issue with gulp-sass. If there's no specific reason to why you are using the latest node, would you mind downgrading for now, if only to see if you can get around your installation troubles?

To do this you can install `n` with
````
sudo npm install -g n
````
and then switch to a different version of node by running
````
sudo n 0.10.32
````
which will downgrade your installed version.

`n` is like an easier package manager specifically for node. To upgrade later on, run `sudo n stable` to go back to the latest stable (0.12 atm).

**Comment by heyitswin** [comment]
Not sure the downgrade fully worked. Screenshot here with the various commands - https://www.dropbox.com/s/8graud89xbnvw3c/Screenshot%202015-02-25%2013.19.17.png?dl=0

**Comment by flovan** [comment]
Your downgrade went through just fine. But I see that NPM was also affected by doing so, and as you can see in the screenshot, you get an "engine" warning by imagemin, causing it to fail further on.

You can upgrade NPM again with `npm update -g npm` (you should end up with v2.6.0 atm), then try installing Headstart again.

**Comment by flovan** [comment]
@heyitswin I don't know if got a chance to upgrade NPM after downgrading Node, but it's worked over here!

**Comment by flovan** [comment]
So is this still an issue for you @heyitswin? I'd like to close this issue if you managed to get Headstart installed, or even if you just lost interest all together (I'd understand!).

**Comment by heyitswin** [comment]
Hey there! Sorry been ultra busy as of late. Would still love to get this resolved but lets close it for now as I probably won't be able to get to it soon enough.

**Comment by flovan** [comment]
No problem. Just let me know when you're back at it, and I'll try to respond timely again! Good luck with your busy schedule :muscle:
