### ISSUE TITLE
Not working on IE9

### ISSUE THREAD

**Issue by kidd001** [flovan/headstart#54]
Hi There,

I build this website http://www.ello.kiwi pretty much based on Headstart, and it completely breaks on IE9, I think Headstart does support IE9, can you please tell me what I have done wrong?

Thanks!

**Comment by kidd001** [comment]
I think I figure that out, it's actually one of the icon font libraries I used screws the whole thing up!

Thanks for all your hard working putting into HeadStart!

**Comment by flovan** [comment]
Hi @kidd001! Glad to see that you managed to solve this one yourself.

By the way, I'm thinking of putting up a section of "built with Headstart" with the next refresh. Can I put the Ello website in there as well? Or is this a private project?

**Comment by kidd001** [comment]
Unfortunately ello has been pulled off due to the board decisions, I don't think this will be the best one to go into your showcase collection.

However I have just completed another project with Headstart, which is http://www.viva.co.nz 

Feel free to put this one up if you want to~~

**Comment by flovan** [comment]
Great, thanks for sharing! it wouldn't feel right to only show off sites that I built myself anyway :) So I'll make sure to include yours!

One quick tip (if I may) — if you add `transform: translateZ(0);` to your `position: fixed;` elements, it will smoothen up scrolling and reduce the [page jank](http://jankfree.org).

**Comment by kidd001** [comment]
Thanks for this great little tip!

**Comment by flovan** [comment]
No problem! I have to add that this is actually a "hack". The proper way to fix page jank caused by `position: fixed;` is with the `will-change` property ([info](https://dev.opera.com/articles/css-will-change-property/)), but that'll probably only be useable in a year or more.
