### ISSUE TITLE
Serving through IP/wifi has odd scrolling behaviors

### ISSUE THREAD

**Issue by heyitswin** [flovan/headstart#57]
If you serve your project via ip/wifi, people scrolling on the page will cause your own page to scroll as they scroll on BOTH the ip and localhost, really weird.

**Comment by artem-malko** [comment]
@flovan @heyitswin Just update browser-sync, there is quite good UI in 2 version. You could control all devices and events from there.

**Comment by flovan** [comment]
@heyitswin If you tunnel your project with `--s --t` or `--s --t=my-project`you'll get a tunneled url which does not share clicking and scrolling with connected clients (or at least it shouldn't; I haven't used that feature in a while :). Also it emulates server latency better.

@artem-malko thanks for pointing that out. I'm focusing on V2 atm, so I don't know if I'll be putting out an extra patch release before that.

**Comment by heyitswin** [comment]
@artem-malko not sure how to update it within the project.
@flovan tried serving it through the tunnel, still not behaving correctly. it's odd that the scrolling is synced, it shouldn't be right?

**Comment by flovan** [comment]
You won't be able to update the browser sync module withing Headstart unless you'd be willing to mess around in the source code (cloning the repo locally and using that as global module).

The synced scrolling/clicking is actually normal. Headstart is a development tool, so it makes testing your site on multiple devices at the same time way easier. Its purpose isn't as much about live-demoing results. A solution might be to lead them to the `export` folder through your IP and local server (eg Mamp).

**Comment by flovan** [comment]
Note to self: check out the V2 UI and/or expose more Browser Sync settings through `.headstartrc` file.

**Comment by heyitswin** [comment]
Got it, I'll try that out. Thanks!
