### ISSUE TITLE
Gem version control

### ISSUE THREAD

**Issue by taracila** [flovan/headstart#59]
Hi,

I haven't seen any information about using bundler.io (or other method) to control gem version control for specific gems. Does this project supports such feature?

Thanks

**Comment by flovan** [comment]
HI @taracila, thank you for your interest.

I think you must've misread something somewhere though, because this is not a Ruby project and (as far as I know) doesn't use any gems other than Ruby, which should be installed manually.

May I ask where you got the idea that this project was using gems?

**Comment by taracila** [comment]
hi @flovan, 

Thanks for replay!

I've seen on this page http://headstart.io/installation that you may install gems "gem install sass" or whanever gem and that will require to specify what version you want to lock on.

That brought me to the idea to have a version control.

Thanks

**Comment by flovan** [comment]
_post-edit: I meant to say "Ruby Sass" above, not just "Ruby"_

Which version of Sass is used doesn't really matter; it's just used for compiling. Besides, I am planning to make this optional and use libsass instead, which is faster.

Thanks for the suggestions though, I appreciate the input :)
