### ISSUE TITLE
"headstart init" stops at "Cleaning up..."

### ISSUE THREAD

**Issue by tiagoborges** [flovan/headstart#60]
I can't start testing headstart because it stops at "Cleaning up..".
I have everything installed( ruby, sass, node, npm .. ), even headstart, but the command "headstart init" won't finish.
Here is the output on the terminal:

 ✝  ~/www/src/headstart/test  headstart init                             
Downloading boilerplate files...
✔ Download complete!
Cleaning up...

**Comment by flovan** [comment]
Hi @tiagoborges,

I'm sorry to hear that you had to encounter a problem on your first try. But I'll do my best to help fix that for you!

Please try running `hs init` again first. Did it tell you that the folder wasn't empty and did it clean up after you confirmed twice? After that initial cleaning, it should attempt to download the boilerplate files again, and, in your case, fail again. When it does fail again, could you run the following command and post back the output:
```
ls
```

That way I can see what it managed to download and hopefully find out where it got stuck.

**Comment by tiagoborges** [comment]
Hello @flovan 

Every time that problem occurred i deleted the folder where i initialized headstart so never told that the folder wasn't empty.
After many attempts i decided to remove everything(npm node4.0.0 nvm), and installed again through linuxbrew and now its all ok.

My best regards.

**Comment by flovan** [comment]
Ok great! Good to hear that you managed to solve the issue. If there's anything I can help you with, feel free to ask!
